MAX_AVATAR_WIDTH = 2000
MAX_AVATAR_HEIGHT = 2000
MAX_IMAGE_WIDTH = 2000
MAX_IMAGE_HEIGHT = 2000
MINIMUM_USERNAME_LENGTH = 3
MINIMUM_PASSWORD_LENGTH = 6
PASSWORD_SALT = "ijaosidj0kj"

IMAGE_MIMETYPES = ["image/jpeg", "image/png"]
IMAGE_EXTENSIONS = [".jpeg", ".png", ".jpg"]

MINIMUM_CREATE_DATE = 4
OTP_CODE_LENGTH = 6
OTP_TIMER = 2
